# II. SHORTENINGS.

library(tidyverse)
library(tidytext)
library(stringi)
library(emo)
library(ggplot2)
library(MASS)
library(pscl)
setwd("C:/Users/jenia/Desktop/PhD Project/2 Practical/_Corpus/LTC")
corpus <- read_csv2("twitter_big_corpus_clean.csv")


# All acronyms

corpus$imo <- str_count(corpus$content_clean_punctuation, "\\bi+m+h*o+\\b")
corpus$btw <- str_count(corpus$content_clean_punctuation, "\\bb+t+w+\\b")
corpus$tbh <- str_count(corpus$content_clean_punctuation, "\\bt+b+h+\\b")
corpus$tbf <- str_count(corpus$content_clean_punctuation, "\\bt+b+f+\\b")
corpus$def <- str_count(corpus$content_clean_punctuation, "\\bd+e+f+\\b")
corpus$ppl <- str_count(corpus$content_clean_punctuation, "\\bp+pl+\\b")
corpus$esp <- str_count(corpus$content_clean_punctuation, "\\be+s+p+\\b")
corpus$rn <- str_count(corpus$content_clean_punctuation, "\\br+n+\\b")
corpus$dw <- str_count(corpus$content_clean_punctuation, "\\bd+w+\\b")
corpus$otoh <- str_count(corpus$content_clean_punctuation, "\\bo+t+o+h+\\b")
corpus$ikr <- str_count(corpus$content_clean_punctuation, "\\bi+k+r+\\b")
corpus$stfu <- str_count(corpus$content_clean_punctuation, "\\bs+t+f+u+\\b")
corpus$af <- str_count(corpus$content_clean_punctuation, "\\ba+f+\\b")
corpus$ffs <- str_count(corpus$content_clean_punctuation, "\\bf+f+s+\\b")
corpus$ur <- str_count(corpus$content_clean_punctuation, "\\bu+r+\\b")
corpus$u <- str_count(corpus$content_clean_punctuation, "\\bu+\\b")
corpus$ily <- str_count(corpus$content_clean_punctuation, "\\bi+l+(y+|u+)\\b")
corpus$gtfo <- str_count(corpus$content_clean_punctuation, "\\bg+t+f+o+\\b")
corpus$sry <- str_count(corpus$content_clean_punctuation, "\\bs+r+y+\\b")
corpus$wtf <- str_count(corpus$content_clean_punctuation, "\\bw+t+f+\\b")
corpus$idk <- str_count(corpus$content_clean_punctuation, "\\bi+d+k+\\b")
corpus$omg <- str_count(corpus$content_clean_punctuation, "\\bo+m+f*g+\\b")
corpus$pls <- str_count(corpus$content_clean_punctuation, "\\bp+l+(s|z)+\\b")
corpus$ofc <- str_count(corpus$content_clean_punctuation, "\\bo+f+c+\\b")


corpus$lol <- str_count(corpus$content_clean_punctuation, "\\bl+o+l+[olz]*\\b")
corpus$lmao <- str_count(corpus$content_clean_punctuation, "\\bl+m+f*a+o+\\b")
corpus$smh <- str_count(corpus$content_clean_punctuation, "\\bs+m+f*h+\\b")
corpus$rofl <- str_count(corpus$content_clean_punctuation, "\\br+o+f+l+\\b")


corpus$inmyopinion <- str_count(corpus$content_clean_punctuation, "i+n+ m+y+( (h+o+n+e+s+t+)|(h+u+m+b+l+e+))* o+p+i+n+i+o+n+")
corpus$bytheway <- str_count(corpus$content_clean_punctuation, "b+y+ t+h+e+ w+a+y+")
corpus$tobehonest <- str_count(corpus$content_clean_punctuation, "t+o+ b+e+ h+o+n+e+s+t+")
corpus$tobefair <- str_count(corpus$content_clean_punctuation, "t+o+ b+e+ f+a+i+r+")
corpus$definitely <- str_count(corpus$content_clean_punctuation, "d+e+f+i+n+i+t+e+l+y+")
corpus$people <- str_count(corpus$content_clean_punctuation, "p+e+o+p+l+e+")
corpus$especially <- str_count(corpus$content_clean_punctuation, "e+s+p+e+c+i+a+l+l+y+")
corpus$rightnow <- str_count(corpus$content_clean_punctuation, "r+i+g+h+t+ n+o+w+")
corpus$dontworry <- str_count(corpus$content_clean_punctuation, "d+o+n+(')*t w+o+r+r+y+")
corpus$ontheotherhand <- str_count(corpus$content_clean_punctuation, "o+n+ t+h+e+ o+t+h+e+r+ h+a+n+d+")
corpus$whatthefuck <- str_count(corpus$content_clean_punctuation, "w+h+a+t+ t+h+e+ f+u+c+k+")
corpus$idontknow <- str_count(corpus$content_clean_punctuation, "i+ d+o+n+(')*t+ k+n+o+w+")
corpus$ohmygod <- str_count(corpus$content_clean_punctuation, "o+h+ m+y+ (f+u+c+k+i+n+g+ )*g+o+d+")
corpus$iknowright <- str_count(corpus$content_clean_punctuation, "i+ k+n+o+w+ r+i+g+h+t+")
corpus$shutthefuckup <- str_count(corpus$content_clean_punctuation, "s+h+u+t+ t+h+e+ f+u+c+k+ u+p+")
corpus$asfuck <- str_count(corpus$content_clean_punctuation, "a+s+ f+(u)*c+k+")
corpus$forfuckssake <- str_count(corpus$content_clean_punctuation, "f+o+r+ f+u+c+k+(')*(s)* s+a+k+e+")
corpus$your <- str_count(corpus$content_clean_punctuation, "(y+o+u+r+)|(y+o+u+(')*r+e+)")
corpus$you <- str_count(corpus$content_clean_punctuation, "\\by+o+u+\\b")
corpus$iloveyou <- str_count(corpus$content_clean_punctuation, "i+ l+o+v+e+ y+o+u+")
corpus$getthefuckout <- str_count(corpus$content_clean_punctuation, "g+e+t+ t+h+e+ f+u+c+k+ o+u+t+")
corpus$sorry <- str_count(corpus$content_clean_punctuation, "s+o+r+r+y+")
corpus$please <-str_count(corpus$content_clean_punctuation, "p+l+e+a+s+e+")
corpus$ofcourse <- str_count(corpus$content_clean_punctuation, "o+f+ c+o+u+r+s+e+")


